services:
  lightrag:
    image: ghcr.io/hkuds/lightrag:latest
    volumes:
      - lightrag_rag_storage:/app/data/rag_storage
      - lightrag_inputs:/app/data/inputs
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.lr2-web.rule=Host(`lr-mediocre.cepta.cloud`)
      - traefik.http.routers.lr2-web.entrypoints=web
      - traefik.http.routers.lr2-web.middlewares=redirect-to-https@file
      - traefik.http.routers.lr2-web.service=lr2-svc
      - traefik.http.routers.lr2-websecure.rule=Host(`lr-mediocre.cepta.cloud`)
      - traefik.http.routers.lr2-websecure.entrypoints=websecure
      - traefik.http.routers.lr2-websecure.tls.certresolver=letsencrypt
      - traefik.http.routers.lr2-websecure.service=lr2-svc
      - traefik.http.services.lr2-svc.loadbalancer.server.port=9621

networks:
  dokploy-network:
    external: true

volumes:
  lightrag_rag_storage:
  lightrag_inputs:
